### ISSUE TITLE
Compatibility with CMS v11?

### ISSUE THREAD

**Issue by valdisiljuconoks** [Geta/DdsAdmin#17]

**Comment by Souperman** [comment]
Hello!

We have tried to install in a CMS 11 site and we get a bad reference - something looking for episerver 9.0.0,.... which we don't have installed or referenced anyway?

Is this officially supported? Do we have to do some work for this?

**Comment by frederikvig** [comment]
Hi, it's not been upgraded to Episerver 11 yet, not sure when it will happen since we're quite busy, but PRs are always welcome.

**Comment by marisks** [comment]
Fixed in version 11.0.0
