### ISSUE TITLE
Suggestion to stop using NuGet frontend packages

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [Geta/DdsAdmin#5]
Would be better not to litter the project root with these packages (JQuery etc), and instead use bower for package management. VS supports it almost out of the box nowadays, I think: http://www.hanselman.com/blog/IntroducingGulpGruntBowerAndNpmSupportForVisualStudio.aspx

**Comment by valdisiljuconoks** [comment]
Closed with 7b557139f0e6315a0ed5b7d1b417476fc15774e2
